#%RAML 1.0
---

title: Mobile PAYE
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/mobile-paye:
  /paye-data:
      get:
        displayName: Get PAYE Data
        description: This endpoint retrieves the PAYE data associated with a given NINO.
        is: [headers.acceptHeader]
        (annotations.scope): "read:mobile-paye"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:mobile-paye" ] } ]
        queryParameters:
          journeyId:
            type: string
            required: false
        responses:
          200:
            body:
              application/json:
                examples:
                  example-1:
                    value: !include examples/get-paye-data-example-1.json